version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/tmatias/miles
    steps:
      - checkout
      - run: go get -u github.com/alecthomas/gometalinter
      - run: gometalinter --install
      - run: gometalinter --config="gometalinter.json"
      - run: go test -v ./...
